-- Phase 12 follow-up: additive PostgreSQL schema only.
-- Review before use. This script does not drop or rewrite existing data.

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_key VARCHAR(64) NOT NULL UNIQUE,
    failure_count INTEGER NOT NULL,
    window_started_at TIMESTAMP NOT NULL,
    blocked_until TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_login_attempt_updated_at
    ON login_attempts (updated_at);

CREATE TABLE IF NOT EXISTS project_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES municipal_projects(id),
    citizen_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_project_flag_project_citizen UNIQUE (project_id, citizen_id)
);

CREATE INDEX IF NOT EXISTS idx_project_flag_project
    ON project_flags (project_id);

CREATE INDEX IF NOT EXISTS idx_project_flag_citizen
    ON project_flags (citizen_id);
