-- Phase 15 data-preserving migration from the original ward/user/project schema.
-- PostgreSQL only. Review and back up the target database before deployment.
-- This script is additive and repeatable; it does not drop tables or delete rows.
-- Execute with psql --single-transaction --set ON_ERROR_STOP=1 --file <this-file>.

-- Phase 4: optional, explainable project-impact input.
ALTER TABLE municipal_projects
    ADD COLUMN IF NOT EXISTS impact_level VARCHAR(255);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'municipal_projects_impact_level_check'
          AND conrelid = 'municipal_projects'::regclass
    ) THEN
        ALTER TABLE municipal_projects
            ADD CONSTRAINT municipal_projects_impact_level_check
            CHECK (impact_level IS NULL OR impact_level IN
                   ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));
    END IF;
END $$;

-- Phase 3/6: complaint persistence and optional one-project association.
CREATE TABLE IF NOT EXISTS complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_user_id BIGINT NOT NULL REFERENCES users(id),
    image_url VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    location_address VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    ai_predicted_issue_type VARCHAR(255),
    ai_confidence DOUBLE PRECISION,
    ai_confidence_level VARCHAR(255),
    ai_suggested_severity VARCHAR(255),
    final_issue_type VARCHAR(255) NOT NULL,
    final_severity VARCHAR(255) NOT NULL,
    prediction_state VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    municipal_project_id BIGINT REFERENCES municipal_projects(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT complaints_ai_predicted_issue_type_check CHECK (
        ai_predicted_issue_type IS NULL OR ai_predicted_issue_type IN
        ('DOMESTIC_TRASH', 'ILLEGAL_PARKING', 'DAMAGED_SIGN', 'POTHOLE',
         'ROAD_CRACK', 'GARBAGE_ACCUMULATION', 'WATERLOGGING',
         'DAMAGED_STREETLIGHT', 'OPEN_MANHOLE', 'OTHER')
    ),
    CONSTRAINT complaints_ai_suggested_severity_check CHECK (
        ai_suggested_severity IS NULL OR ai_suggested_severity IN
        ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT complaints_final_issue_type_check CHECK (
        final_issue_type IN ('DOMESTIC_TRASH', 'ILLEGAL_PARKING', 'DAMAGED_SIGN',
        'POTHOLE', 'ROAD_CRACK', 'GARBAGE_ACCUMULATION', 'WATERLOGGING',
        'DAMAGED_STREETLIGHT', 'OPEN_MANHOLE', 'OTHER')
    ),
    CONSTRAINT complaints_final_severity_check CHECK (
        final_severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT complaints_prediction_state_check CHECK (
        prediction_state IN ('CONFIRMED', 'EDITED', 'REJECTED', 'MANUAL')
    ),
    CONSTRAINT complaints_status_check CHECK (status IN ('SUBMITTED')),
    CONSTRAINT complaints_ai_confidence_range_check CHECK (
        ai_confidence IS NULL OR ai_confidence BETWEEN 0.0 AND 1.0
    )
);

CREATE INDEX IF NOT EXISTS idx_complaint_reporting_user
    ON complaints (reporting_user_id);
CREATE INDEX IF NOT EXISTS idx_complaint_status
    ON complaints (status);
CREATE INDEX IF NOT EXISTS idx_complaint_municipal_project
    ON complaints (municipal_project_id);

-- Phase 12: persistent login throttling.
CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_key VARCHAR(64) NOT NULL UNIQUE,
    failure_count INTEGER NOT NULL,
    window_started_at TIMESTAMP NOT NULL,
    blocked_until TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_login_attempt_updated_at
    ON login_attempts (updated_at);

-- Phase 12: one citizen flag per project.
CREATE TABLE IF NOT EXISTS project_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES municipal_projects(id),
    citizen_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_project_flag_project_citizen UNIQUE (project_id, citizen_id)
);

CREATE INDEX IF NOT EXISTS idx_project_flag_project
    ON project_flags (project_id);
CREATE INDEX IF NOT EXISTS idx_project_flag_citizen
    ON project_flags (citizen_id);

-- Existing query paths and foreign-key support not supplied by PostgreSQL
-- automatically. Composite indexes retain their left-prefix filtering use.
CREATE INDEX IF NOT EXISTS idx_user_ward_role
    ON users (ward_id, role);
CREATE INDEX IF NOT EXISTS idx_user_role
    ON users (role);
CREATE INDEX IF NOT EXISTS idx_project_ward_created_at
    ON municipal_projects (ward_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_ward_status
    ON municipal_projects (ward_id, status);
CREATE INDEX IF NOT EXISTS idx_project_ward_type
    ON municipal_projects (ward_id, project_type);
CREATE INDEX IF NOT EXISTS idx_project_assigned_worker
    ON municipal_projects (assigned_worker_id);
CREATE INDEX IF NOT EXISTS idx_project_created_by
    ON municipal_projects (created_by_id);
CREATE INDEX IF NOT EXISTS idx_project_flagged_by_ward
    ON municipal_projects (ward_id) WHERE flagged = true;
CREATE INDEX IF NOT EXISTS idx_project_photos_project
    ON project_photos (project_id);
CREATE INDEX IF NOT EXISTS idx_complaint_created_at
    ON complaints (created_at DESC);

